name: Build windows package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Poetry
        run: |
          pipx install "poetry>=1.7.0"
          pipx install poethepoet
      - name: Set up Python
        id: pysetup
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install package and dependencies
        run: |
          cd src
          poetry env use '${{ steps.pysetup.outputs.python-path }}'
          poetry install --with build --without dev
      - name: Build package
        run: |
          poetry run cxfreeze bdist_msi
      - name: Publish Release
        uses: softprops/action-gh-release@master
        id: release
        with:
          prerelease: ${{startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc')}}
          generate_release_notes: true
          files: |
            ./src/dist/Redacted Video*.msi
